/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.team1.inventory;

/**
 *
 * @author team1
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final java.sql.Connection conn = Koneksi.createConnection();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loadKategori();
        loadBarang();
        loadTransaksi();
    }

    private void loadKategoriToCombo() {
        cmbKategoriBarang.removeAllItems();
        try {
            if (conn != null) {
                java.sql.ResultSet res = Kategori.get(conn);
                while (res != null && res.next()) {
                    cmbKategoriBarang.addItem(res.getString("NamaKategori"));
                }
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading kategori to combo", e);
        }
    }

    private void loadTransaksiToCombo() {
        cmbBarangTransaksi.removeAllItems();
        try {
            if (conn != null) {
                java.sql.ResultSet res = Barang.get(conn);
                while (res != null && res.next()) {
                    cmbBarangTransaksi.addItem(res.getInt("IdBarang") + " - " + res.getString("NamaBarang"));
                }
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading barang to combo", e);
        }
    }

    private void loadBarang() {
        loadTransaksiToCombo();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBarang.getModel();
        model.setRowCount(0);
        try {
            if (conn != null) {
                java.sql.ResultSet res = Barang.get(conn);
                while (res != null && res.next()) {
                    model.addRow(new Object[]{
                        res.getInt("IdBarang"),
                        res.getString("NamaBarang"),
                        res.getString("NamaKategori"),
                        res.getInt("JumlahBarang")
                    });
                }
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading barang", e);
        }
    }

    private void loadKategori() {
        loadKategoriToCombo();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKategori.getModel();
        model.setRowCount(0);
        try {
            if (conn != null) {
                java.sql.ResultSet res = Kategori.get(conn);
                while (res != null && res.next()) {
                    model.addRow(new Object[]{
                        res.getInt("IdKategori"),
                        res.getString("NamaKategori")
                    });
                }
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading kategori", e);
        }
    }

    private void loadTransaksi() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblTransaksi.getModel();
        model.setRowCount(0);
        try {
            if (conn != null) {
                java.sql.ResultSet res = Transaksi.get(conn);
                while (res != null && res.next()) {
                    model.addRow(new Object[]{
                        res.getInt("IdTransaksi"),
                        res.getString("NamaBarang"),
                        res.getString("NamaKategori"),
                        res.getString("TipeTransaksi"),
                        res.getInt("JumlahTransaksi"),
                        res.getString("Pesan"),
                        res.getTimestamp("Timestamp")
                    });
                }
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading transaksi", e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelKategori = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCariKategori = new javax.swing.JTextField();
        btnCariKategori = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNamaKategori = new javax.swing.JTextField();
        btnSimpanKategori = new javax.swing.JButton();
        btnEditKategori = new javax.swing.JButton();
        btnHapusKategori = new javax.swing.JButton();
        btnResetKategori = new javax.swing.JButton();
        panelBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCariBarang = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbKategoriBarang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtStokBarang = new javax.swing.JTextField();
        btnSimpanBarang = new javax.swing.JButton();
        btnEditBarang = new javax.swing.JButton();
        btnHapusBarang = new javax.swing.JButton();
        btnResetBarang = new javax.swing.JButton();
        panelTransaksi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCariTransaksi = new javax.swing.JTextField();
        btnCariTransaksi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cmbBarangTransaksi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbTipeTransaksi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtJumlahTransaksi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPesanTransaksi = new javax.swing.JTextField();
        btnSimpanTransaksi = new javax.swing.JButton();
        btnResetTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Inventory");

        jLabel1.setText("Cari :");

        btnCariKategori.setText("Cari");
        btnCariKategori.addActionListener(this::btnCariKategoriActionPerformed);

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Kategori"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKategori);

        jLabel2.setText("Nama Kategori :");

        btnSimpanKategori.setText("Simpan");
        btnSimpanKategori.addActionListener(this::btnSimpanKategoriActionPerformed);

        btnEditKategori.setText("Edit");
        btnEditKategori.addActionListener(this::btnEditKategoriActionPerformed);

        btnHapusKategori.setText("Hapus");
        btnHapusKategori.addActionListener(this::btnHapusKategoriActionPerformed);

        btnResetKategori.setText("Reset");
        btnResetKategori.addActionListener(this::btnResetKategoriActionPerformed);

        javax.swing.GroupLayout panelKategoriLayout = new javax.swing.GroupLayout(panelKategori);
        panelKategori.setLayout(panelKategoriLayout);
        panelKategoriLayout.setHorizontalGroup(
            panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKategoriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKategoriLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariKategori))
                    .addGroup(panelKategoriLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaKategori)
                            .addGroup(panelKategoriLayout.createSequentialGroup()
                                .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimpanKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapusKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResetKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelKategoriLayout.setVerticalGroup(
            panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKategoriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCariKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariKategori))
                .addGap(18, 18, 18)
                .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelKategoriLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanKategori)
                            .addComponent(btnEditKategori))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapusKategori)
                            .addComponent(btnResetKategori))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kategori", panelKategori);

        jLabel3.setText("Cari :");

        btnCariBarang.setText("Cari");
        btnCariBarang.addActionListener(this::btnCariBarangActionPerformed);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Barang", "Kategori", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBarang);

        jLabel4.setText("Nama Barang :");

        jLabel5.setText("Kategori :");

        jLabel6.setText("Stok Awal :");

        btnSimpanBarang.setText("Simpan");
        btnSimpanBarang.addActionListener(this::btnSimpanBarangActionPerformed);

        btnEditBarang.setText("Edit");
        btnEditBarang.addActionListener(this::btnEditBarangActionPerformed);

        btnHapusBarang.setText("Hapus");
        btnHapusBarang.addActionListener(this::btnHapusBarangActionPerformed);

        btnResetBarang.setText("Reset");
        btnResetBarang.addActionListener(this::btnResetBarangActionPerformed);

        javax.swing.GroupLayout panelBarangLayout = new javax.swing.GroupLayout(panelBarang);
        panelBarang.setLayout(panelBarangLayout);
        panelBarangLayout.setHorizontalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBarang))
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txtNamaBarang)
                            .addGroup(panelBarangLayout.createSequentialGroup()
                                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimpanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResetBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addComponent(cmbKategoriBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(txtStokBarang))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelBarangLayout.setVerticalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBarang))
                .addGap(18, 18, 18)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanBarang)
                            .addComponent(btnEditBarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapusBarang)
                            .addComponent(btnResetBarang))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Barang", panelBarang);

        jLabel7.setText("Cari :");

        btnCariTransaksi.setText("Cari");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Barang", "Kategori", "Tipe", "Jumlah", "Pesan", "Waktu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTransaksi);

        jLabel8.setText("Barang :");

        jLabel9.setText("Tipe :");

        cmbTipeTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masuk", "Keluar" }));

        jLabel10.setText("Jumlah :");

        jLabel11.setText("Pesan :");

        btnSimpanTransaksi.setText("Simpan");
        btnSimpanTransaksi.addActionListener(this::btnSimpanTransaksiActionPerformed);

        btnResetTransaksi.setText("Reset");
        btnResetTransaksi.addActionListener(this::btnResetTransaksiActionPerformed);

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariTransaksi))
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(panelTransaksiLayout.createSequentialGroup()
                                .addComponent(btnSimpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnResetTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(cmbBarangTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(txtJumlahTransaksi)
                            .addComponent(jLabel11)
                            .addComponent(txtPesanTransaksi)
                            .addComponent(cmbTipeTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariTransaksi))
                .addGap(18, 18, 18)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBarangTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanTransaksi)
                            .addComponent(btnResetTransaksi))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi", panelTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKategoriActionPerformed
        String nama = txtNamaKategori.getText().trim();
        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama kategori tidak boleh kosong!");
            return;
        }

        if (conn != null) {
            Kategori.create(conn, nama);
            txtNamaKategori.setText("");
            loadKategori();
        }
    }//GEN-LAST:event_btnSimpanKategoriActionPerformed

    private void btnHapusKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKategoriActionPerformed
        int selectedRow = tblKategori.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kategori yang ingin dihapus!");
            return;
        }

        int id = (int) tblKategori.getValueAt(selectedRow, 0);
        String nama = (String) tblKategori.getValueAt(selectedRow, 1);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus kategori '" + nama + "'?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (conn != null) {
                Kategori.delete(conn, id);
                txtNamaKategori.setText("");
                loadKategori();
            }
        }
    }//GEN-LAST:event_btnHapusKategoriActionPerformed

    private void btnEditKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKategoriActionPerformed
        int selectedRow = tblKategori.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kategori yang ingin diubah!");
            return;
        }

        int id = (int) tblKategori.getValueAt(selectedRow, 0);
        String nama = txtNamaKategori.getText().trim();

        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama kategori tidak boleh kosong!");
            return;
        }

        if (conn != null) {
            Kategori.update(conn, id, nama);
            txtNamaKategori.setText("");
            loadKategori();
        }
    }//GEN-LAST:event_btnEditKategoriActionPerformed

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseClicked
        int selectedRow = tblKategori.getSelectedRow();
        if (selectedRow != -1) {
            txtNamaKategori.setText(tblKategori.getValueAt(selectedRow, 1).toString());
        }
    }//GEN-LAST:event_tblKategoriMouseClicked

    private void btnCariKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKategoriActionPerformed
        String query = txtCariKategori.getText().trim();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKategori.getModel();
        model.setRowCount(0);

        try {
            if (conn != null) {
                java.sql.ResultSet res = Kategori.find(conn, query);
                while (res != null && res.next()) {
                    model.addRow(new Object[]{
                        res.getInt("IdKategori"),
                        res.getString("NamaKategori")
                    });
                }
            }
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error searching kategori", ex);
        }
    }//GEN-LAST:event_btnCariKategoriActionPerformed

    private void btnResetKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKategoriActionPerformed
        txtCariKategori.setText("");
        txtNamaKategori.setText("");
        loadKategori();
    }//GEN-LAST:event_btnResetKategoriActionPerformed


    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        String query = txtCariBarang.getText().trim();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBarang.getModel();
        model.setRowCount(0);

        try {
            if (conn != null) {
                java.sql.ResultSet res = Barang.find(conn, query);
                while (res != null && res.next()) {
                    model.addRow(new Object[]{
                        res.getInt("IdBarang"),
                        res.getString("NamaBarang"),
                        res.getString("NamaKategori"),
                        res.getInt("JumlahBarang")
                    });
                }
            }
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error searching barang", ex);
        }
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void btnSimpanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBarangActionPerformed
        String namaBarang = txtNamaBarang.getText().trim();
        String stokText = txtStokBarang.getText().trim();
        String namaKategori = (String) cmbKategoriBarang.getSelectedItem();

        if (namaBarang.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama barang tidak boleh kosong!");
            return;
        }

        int stokAwal = 0;
        if (!stokText.isEmpty()) {
            try {
                stokAwal = Integer.parseInt(stokText);
                if (stokAwal < 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Stok awal tidak boleh negatif!");
                    return;
                }
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Stok awal harus berupa angka valid!");
                return;
            }
        }

        if (namaKategori == null || namaKategori.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kategori terlebih dahulu!");
            return;
        }

        try {
            if (conn != null) {
                // Find exact IdKategori
                int idKategori = -1;
                try (java.sql.PreparedStatement stmt = conn.prepareStatement("SELECT IdKategori FROM Kategori WHERE NamaKategori = ?")) {
                    stmt.setString(1, namaKategori);
                    try (java.sql.ResultSet res = stmt.executeQuery()) {
                        if (res.next()) {
                            idKategori = res.getInt("IdKategori");
                        }
                    }
                }

                if (idKategori == -1) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Kategori tidak ditemukan di database!");
                    return;
                }

                Barang.create(conn, idKategori, namaBarang, stokAwal);
                txtNamaBarang.setText("");
                txtStokBarang.setText("");
                loadBarang();
                loadTransaksi();
            }
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error saving barang", ex);
        }
    }//GEN-LAST:event_btnSimpanBarangActionPerformed

    private void btnHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBarangActionPerformed
        int selectedRow = tblBarang.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang yang ingin dihapus!");
            return;
        }

        int id = (int) tblBarang.getValueAt(selectedRow, 0);
        String nama = (String) tblBarang.getValueAt(selectedRow, 1);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus barang '" + nama + "'?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (conn != null) {
                Barang.delete(conn, id);
                txtNamaBarang.setText("");
                txtStokBarang.setText("");
                loadBarang();
                loadTransaksi();
            }
        }
    }//GEN-LAST:event_btnHapusBarangActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        int selectedRow = tblBarang.getSelectedRow();
        if (selectedRow != -1) {
            txtNamaBarang.setText(tblBarang.getValueAt(selectedRow, 1).toString());
            cmbKategoriBarang.setSelectedItem(tblBarang.getValueAt(selectedRow, 2).toString());
            // Stok awal tidak diubah saat update barang karena update stok lewat transaksi
            txtStokBarang.setText(tblBarang.getValueAt(selectedRow, 3).toString());
            txtStokBarang.setEnabled(false); // disable edit stok
        }
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBarangActionPerformed
        int selectedRow = tblBarang.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang yang ingin diubah!");
            return;
        }

        int id = (int) tblBarang.getValueAt(selectedRow, 0);
        String namaBarang = txtNamaBarang.getText().trim();
        String namaKategori = (String) cmbKategoriBarang.getSelectedItem();

        if (namaBarang.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama barang tidak boleh kosong!");
            return;
        }

        if (namaKategori == null || namaKategori.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kategori terlebih dahulu!");
            return;
        }

        try {
            if (conn != null) {
                int idKategori = -1;
                try (java.sql.PreparedStatement stmt = conn.prepareStatement("SELECT IdKategori FROM Kategori WHERE NamaKategori = ?")) {
                    stmt.setString(1, namaKategori);
                    try (java.sql.ResultSet res = stmt.executeQuery()) {
                        if (res.next()) {
                            idKategori = res.getInt("IdKategori");
                        }
                    }
                }

                if (idKategori == -1) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Kategori tidak ditemukan di database!");
                    return;
                }

                Barang.update(conn, id, idKategori, namaBarang);
                txtNamaBarang.setText("");
                txtStokBarang.setText("");
                txtStokBarang.setEnabled(true);
                loadBarang();
                loadTransaksi();
            }
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error updating barang", ex);
        }
    }//GEN-LAST:event_btnEditBarangActionPerformed

    private void btnResetBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBarangActionPerformed
        txtCariBarang.setText("");
        txtNamaBarang.setText("");
        txtStokBarang.setText("");
        txtStokBarang.setEnabled(true);
        if (cmbKategoriBarang.getItemCount() > 0) {
            cmbKategoriBarang.setSelectedIndex(0);
        }
        loadBarang();
    }//GEN-LAST:event_btnResetBarangActionPerformed

    private void btnSimpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTransaksiActionPerformed
        String selectedBarang = (String) cmbBarangTransaksi.getSelectedItem();
        String tipe = (String) cmbTipeTransaksi.getSelectedItem();
        String jumlahText = txtJumlahTransaksi.getText().trim();

        if (selectedBarang == null || selectedBarang.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu!");
            return;
        }

        if (jumlahText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Jumlah transaksi tidak boleh kosong!");
            return;
        }

        int jumlah = 0;
        try {
            jumlah = Integer.parseInt(jumlahText);
            if (jumlah <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Jumlah transaksi harus lebih dari 0!");
                return;
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Jumlah transaksi harus berupa angka valid!");
            return;
        }

        int idBarang = Integer.parseInt(selectedBarang.split(" - ")[0]);

        try {
            if (conn != null) {
                // If "Keluar", check if enough stock
                if ("Keluar".equals(tipe)) {
                    try (java.sql.PreparedStatement stmt = conn.prepareStatement("SELECT JumlahBarang FROM Barang WHERE IdBarang = ?")) {
                        stmt.setInt(1, idBarang);
                        try (java.sql.ResultSet res = stmt.executeQuery()) {
                            if (res.next()) {
                                int stok = res.getInt("JumlahBarang");
                                if (stok < jumlah) {
                                    javax.swing.JOptionPane.showMessageDialog(this, "Stok tidak mencukupi! Stok saat ini: " + stok);
                                    return;
                                }
                            }
                        }
                    }
                }

                String pesan = txtPesanTransaksi.getText().trim();
                Transaksi.create(conn, idBarang, tipe, jumlah, pesan);
                txtJumlahTransaksi.setText("");
                txtPesanTransaksi.setText("");
                loadTransaksi();
                loadBarang(); // Refresh barang to show updated stock
            }
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error saving transaksi", ex);
        }
    }//GEN-LAST:event_btnSimpanTransaksiActionPerformed

    private void btnResetTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTransaksiActionPerformed
        txtCariTransaksi.setText("");
        txtJumlahTransaksi.setText("");
        txtPesanTransaksi.setText("");
        if (cmbBarangTransaksi.getItemCount() > 0) {
            cmbBarangTransaksi.setSelectedIndex(0);
        }
        cmbTipeTransaksi.setSelectedIndex(0);
        loadTransaksi();
    }//GEN-LAST:event_btnResetTransaksiActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnCariKategori;
    private javax.swing.JButton btnCariTransaksi;
    private javax.swing.JButton btnEditBarang;
    private javax.swing.JButton btnEditKategori;
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnHapusKategori;
    private javax.swing.JButton btnResetBarang;
    private javax.swing.JButton btnResetKategori;
    private javax.swing.JButton btnResetTransaksi;
    private javax.swing.JButton btnSimpanBarang;
    private javax.swing.JButton btnSimpanKategori;
    private javax.swing.JButton btnSimpanTransaksi;
    private javax.swing.JComboBox<String> cmbBarangTransaksi;
    private javax.swing.JComboBox<String> cmbKategoriBarang;
    private javax.swing.JComboBox<String> cmbTipeTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelBarang;
    private javax.swing.JPanel panelKategori;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtCariKategori;
    private javax.swing.JTextField txtCariTransaksi;
    private javax.swing.JTextField txtJumlahTransaksi;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaKategori;
    private javax.swing.JTextField txtPesanTransaksi;
    private javax.swing.JTextField txtStokBarang;
    // End of variables declaration//GEN-END:variables
}
